//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokerDashboard.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GamePlayer
    {
        public long GameId { get; set; }
        public long PlayerId { get; set; }
        public Nullable<long> Rank { get; set; }
        public long Prize { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual Player Player { get; set; }
    }
}
