//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokerDashboard.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public Player()
        {
            this.GamePlayers = new HashSet<GamePlayer>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public string WindowsLogin { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<GamePlayer> GamePlayers { get; set; }
    }
}
